---
apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: client
spec:
  containers:
  - name: client
    image: rucio/rucio-clients:latest
    volumeMounts:
    - name: user-cert
      mountPath: /tmp/usercert.pem
      subPath: tls.cert
    - name: user-cert
      mountPath: /tmp/userkey.pem
      subPath: tls.key
    - name: ca-cert
      mountPath: /etc/grid-security/certificates/5fca1cb1.0
      subPath: tls.cert
    command: ["/bin/bash"]
    args: ["-c", "mkdir -p /opt/rucio/etc; cp /tmp/usercert.pem /opt/rucio/etc/usercert.pem; cp /tmp/userkey.pem /opt/rucio/etc/userkey.pem; chmod 400 /opt/rucio/etc/userkey.pem; echo ready; while true; do sleep 60; done"]
    env:
    - name: RUCIO_CFG_CLIENT_RUCIO_HOST
      value: http://server-rucio-server
    - name: RUCIO_CFG_CLIENT_AUTH_HOST
      value: http://server-rucio-server
    - name: RUCIO_CFG_CLIENT_AUTH_TYPE
      value: userpass
    - name: RUCIO_CFG_CLIENT_USERNAME
      value: tutorial
    - name: RUCIO_CFG_CLIENT_PASSWORD
      value: secret1R
    - name: RUCIO_CFG_CLIENT_ACCOUNT
      value: root
    - name: RUCIO_CFG_CLIENT_CERT
      value: /opt/rucio/etc/usercert.pem
    - name: RUCIO_CFG_CLIENT_CA_CERT
      value: /etc/grid-security/certificates/5fca1cb1.0
    - name: RUCIO_CFG_CLIENT_KEY
      value: /opt/rucio/etc/userkey.pem
    - name: RUCIO_CFG_CLIENT_X509_PROXY
      value: $X509_USER_PROXY
    - name: X509_USER_CERT
      value: /opt/rucio/etc/usercert.pem
    - name: X509_USER_KEY
      value: /opt/rucio/etc/userkey.pem
  volumes:
  - name: user-cert
    secret:
      secretName: ruciouser-cert
  - name: ca-cert
    secret:
      secretName: ca-cert
      defaultMode: 0644
     

