apiVersion: v1
kind: Secret
metadata:
  name: clients-user-key
  namespace: rucio
type: Opaque
data:
  userkey.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRFVjTHI3elp2ZFRzeFoKTXNWbGxIaUhMRFpIRnNwMUx5aEZMcnZQYnhwb1E0STlkdHJOaFBKQkI3TzJOWVNMRVZ5RnhvUm5wV0g2akZNOQpCZzBuWkMxM3FUOXVKcnpyNUZ0WlBBZktlK1ZKZTNERWtlYnpFNkRuY3lpSmtacHF0eHJKOERyM1IxTXlydXA1CnhaK0JGL1FweURYcURNWnBoUG93RU1TY09tbW9TWTFjZkplbTFYdkZGSHl1L0t2NWNZWW44YlBrY3Z5Z2ZUb1AKazlBY1ppU0pwOW0rZlE1NW0wTk5wS3RHQXRVeUxrKzlVU2hzeFNZZk9XQUhPUjUrZ1IwRHN2dGtaRWxGTThlNAp2WjQrc1B6UWpXekhranlFSVpEZE1vVXVHOFFtclYrZDRFM1JvQ1pSM09ZT0VmeWhtVXZLQnlKSmVJeno3ajJ1Clg2aHNUc1l4QWdNQkFBRUNnZ0VBWnd4Znh6RVBRQ1N1L3oyZmZ3eXNBbld4eG40SnF4bzY0SVF3MmdnOHVRSzIKTkhabzRIUnl4cFNqMmVqUDZGMTlrZTZmMzE3Ynpoc3ZiVlI0SVBsNURLaHVlbElVSmlEWkpzbjF4WVNmemlzdwpva2xieStGamxhSElzaUtNMHVNSy9aV29KTGJXWnFsdVY2OURGZTIycEdYWHNUYU5NRFl1M2cza01Sd3NrRkpxCjhURjhXaGVNdWNaRkhTWHpKUXJCRlNMcWJXaTF5eFVtRVAwYklzLzJ0VklGTndpaWNoUGYrYllUTlVJYmllOFMKV1hpSDJzVm9qN2VIOS9lWE9PUStGYWhJTGZWSDdhWGFIeHVLNVQzbG82YkhuUk85MjkvRCs1M0EwTU9CU3hGbQp1b0tIbXJnN2k4bnFDL3RyVHJoandxMjZaR2NKQlhaTWFuNVE0Mm9oK1FLQmdRRHlxL0UvMVJFMTdvS252ek1ECmYzMndIRURNSTF3Y0Vnei9va04yejJIeXBkMjJiUGdOdzZYY2ZBaEtHaXM4OFpheTV3Y1BWNEZxWCtYTWxkeTAKdnRWWkt1ZlZVcktjai93ZXp6NWtlNU1vMUZsQ09OY2NoL2x6TkF3LzI2QjU5SDZXNEdkWmdWQVB0M0dvaGlQUgo1T2JuQXRBL3NXUCt1SkF1UXhrY1AxQXdEd0tCZ1FEZ0c3bG9zNW45SUZ1aEJEL2ZIWEV6cTBBS1JDSGFBTWYrCnVOc3g3RThYR0g5bk9rZTlyRk1uQndoMUhZL2Fnc1AvWmtpS2lZVjdjY0s5YnpUVThiOTBWWGI3VG5zMHd1U1cKcUJndWJ2MTI4anNoTzhhVnJDRnF3NEFqRitzeEZTZWFScUp4RXhCdnUyQWc5ZGNEUHF3WHErOTYzMUlGQWVSRgpHK3E3NWl0bHZ3S0JnUUNKbEFlVEc5WEZFTEtNTGE3YlJkVlpHYnQyd0hsQkJNN1B3d3VpZVJKYndjTi80Q21GCmpDMGxZa0JFMnE4MnZ2U2orcXlhK3c1STQ1Tmh1SGpIRkFYYXBxT0c0bnFXbmw3ZWpMb2Z0NXVIbzFQellrdzYKUmJDYnFwOWpPTDJ6Um5UYVR1RG84cElVUnZrdUJOYWI4YjBpclFxcGdZVmliUHA0Nzl0MWswTi82d0tCZ0JtUwpVRWVvSnF3Qll6TXVQdk9BY29oSXhCZm55azBMeGNaRTVZMyt2cytOMWd1N1ZMQkoxM3NlakZLQXV3ZGQ0R3RtCkNtVDBhQ3k3d0ZMSk82Z0lwYVhxa3BiK1Q0U25zRm1ZZUpuanhEd3NTNTd4S1NtdTZHazhRWVMvbC9DVHoxOEYKTEVmbXV2dGswQVV5eUFQd3hNWTJzaTY5Q0tqVm5HeGVVUng3bVB3VkFvR0JBSjdBWG50K0VGdStsYmg0WG1OUQp2K1FoUUFxVEoyanFhQnFjWk44OENhWjg5YXdQcHdaRE1FdWIxUWRzVFU2bUNXUWt2L0psbXcxNFAyTTBubC9PCkljZnZMZTZGbHZJVU9tRStxZC84Uk5Fcy9HUHhoRFJ4Sy9reGJ5a1Zsa0VzMnQ0eDMyLzhPL05SbjRKUGJVUVQKS2Z1WDdueUJBU1h4NEhzbTRreEJIUURmCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: Secret
metadata:
  name: clients-user-cert
  namespace: rucio
type: Opaque
data:
  usercert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMxRENDQWJ5Z0F3SUJBZ0lVVlhwWnhmdGFVTXdyd2drNndZUjFjR2wwbHBJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF3d1VVblZqYVc4Z1JHVjJaV3h2Y0cxbGJuUWdRMEV3SGhjTk1Ua3dPREV5TVRRegpOek0xV2hjTk5EWXhNakkzTVRRek56TTFXakFWTVJNd0VRWURWUVFEREFwU2RXTnBieUJWYzJWeU1JSUJJakFOCkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTFIQzYrODJiM1U3TVdUTEZaWlI0aHl3MlJ4YksKZFM4b1JTNjd6MjhhYUVPQ1BYYmF6WVR5UVFlenRqV0VpeEZjaGNhRVo2Vmgrb3hUUFFZTkoyUXRkNmsvYmlhOAo2K1JiV1R3SHludmxTWHR3eEpIbTh4T2c1M01vaVpHYWFyY2F5ZkE2OTBkVE1xN3FlY1dmZ1JmMEtjZzE2Z3pHCmFZVDZNQkRFbkRwcHFFbU5YSHlYcHRWN3hSUjhydnlyK1hHR0ovR3o1SEw4b0gwNkQ1UFFIR1lraWFmWnZuME8KZVp0RFRhU3JSZ0xWTWk1UHZWRW9iTVVtSHpsZ0J6a2Vmb0VkQTdMN1pHUkpSVFBIdUwyZVByRDgwSTFzeDVJOApoQ0dRM1RLRkxodkVKcTFmbmVCTjBhQW1VZHptRGhIOG9abEx5Z2NpU1hpTTgrNDlybCtvYkU3R01RSURBUUFCCm94SXdFREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRXhaTGcycTN5QkYKZ0pPL0poa0NxTHp0OEVTczV0Z0EyOC9XZnJyMUVRU0tmMmFZc1RWb0llOEVYN01nQThmeE5EU0pxMGwvWGZtYQo2UU9yR0UzR2FaNzZ0MlFwRmVuZUJGQXNYZTFBc3laL2ZaeTRKc2gvTUxYeDFLWHFRb05jQVZwYTBQQ1ZqdGxjCmU5TlVTWU9lc25NUFV6TEpDS1NnOC9LbEVBRUpQSVU3KzdhYldGVFpPcDI2TFQ1ZEhzViswbVRSNm9WT3piT04KVjdNWkhieXkybk9VOGdLTFVBK0ZwTnNqQy9Qb3RSSmdtWHhoTnZ2d1o2RnpMbUlWOXg2MG8wUHA1eFhJeEpNLwpUWmQ1azFIVFpsc1p5RmZZUGdHQ3k3S2ZKOFdGWW5ZV1lnSFo4ajVRTGJOeXBScTh6RmxZMWNnblBXVmtIcmFKCnRMY3ZPSEJTZlU0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: clients-rucio-ca-bundle
  namespace: rucio
type: Opaque
data:
  ca.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lVSzdtbEtOZ05aemcxdjB1RUVVd055T1ZQQW9Vd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF3d1VVblZqYVc4Z1JHVjJaV3h2Y0cxbGJuUWdRMEV3SGhjTk1Ua3dPREE1TVRneApNREF6V2hjTk5EWXhNakkwTVRneE1EQXpXakFmTVIwd0d3WURWUVFEREJSU2RXTnBieUJFWlhabGJHOXdiV1Z1CmRDQkRRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLSVZJVGVhbUNyWXNoWUkKcStPOXFmazUvcXpMWW9ZNEd5YW5OZDNQNWN2d3BvRE1tNFlJdzJ1U0FUVGpwTGw4WDZqYXdnNG9jWFNPYWllTwpoR3RXUDZQbTI2Z1FOd1ZkZDZtT2IvYzdadmFPWDlrajRUUk4xTC90SU8xQXpBdHVUaG9SdmtXbzBUY3B3YmVaCkpZK0FjSU5KV3BqNVpNb2JMKzBRdlVjN1EydXB6RVk5K3Q3Q1VCRnVISEplckpROTVnUElVYjhqUklTdWRwVC8KK010TVZiRjFoRm1iZHVFTEZYM0EyYldjZmd2SVJRNGRUTEFMdkloVzJQS3ZTU3lSME50bzRzaXFmMk42eEdYSQoyR29NbkR5SzlTTW9NYS9YSmlLWXA5WTB1bGk1aUd2OEtkeTB3YnhieGhsSlVESnRNSWp3TjdwaXZPMmkxNi9XCm9tTjhCaTBDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkViaGNpUTI4b2tvek16K2hhaTl5bHI0c2QyME1COEcKQTFVZEl3UVlNQmFBRkViaGNpUTI4b2tvek16K2hhaTl5bHI0c2QyME1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQXRsc0w0ZjljS1lJZmZ6TWI1VjZSdjNTaGNBdGZnclVvMGNhMXMwCnM0U0lnYVZJa0RDZENnYjN0R2Z3VEk4OVJ1UDRCSzFzdVlhZXpESGRoNGJJaTM2L2xGSW1VODhkME51eHFqU3IKaVJkcnJTUXJjUlA5K3ppMUVpbnUwR0FrcHRqV1h4eExXaHl2STRMZVZsZDM1WWd6REJzSVBZRFJmZmJvV2VSRgpCQmx4NzdWY3lkTFNGbnBuUjZLNXJudm9QMERsUGJRSk9FaTJseTQyL2tkalp4dlNkVEcxaGhxeGVIcTFSTVYxCk1LdEM5cWxqaGtaOEJBanYxbnpHa3UvY3pSUVQveUFLbVBTVXZoQTFXNmx6dk43YnVwNVc0SFFLY3dIY2FJQ1QKMTF1LzlkNVhlUFRSZEl0cVFxSW5KM1hTdkV3Y1QvTTRHeHViOHZ6Z0hrUnlCQ0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: rucio
  labels:
    app: client
spec:
  containers:
  - name: client
    image: rucio/rucio-clients:latest
    volumeMounts:
    - name: usercert
      mountPath: /tmp/usercert.pem
      subPath: usercert.pem
    - name: userkey
      mountPath: /tmp/userkey.pem
      subPath: userkey.pem
    - name: ca
      mountPath: /etc/grid-security/certificates/5fca1cb1.0
      subPath: ca.pem
    command: ["/bin/bash"]
    args: ["-c", "mkdir -p /opt/rucio/etc; cp /tmp/usercert.pem /opt/rucio/etc/usercert.pem; cp /tmp/userkey.pem /opt/rucio/etc/userkey.pem; chmod 400 /opt/rucio/etc/userkey.pem; echo ready; while true; do sleep 60; done"]
    env:
    - name: RUCIO_CFG_RUCIO_HOST
      value: http://server-rucio-server
    - name: RUCIO_CFG_AUTH_HOST
      value: http://server-rucio-server-auth
    - name: RUCIO_CFG_AUTH_TYPE
      value: userpass
    - name: RUCIO_CFG_USERNAME
      value: tutorial
    - name: RUCIO_CFG_PASSWORD
      value: secret1R
    - name: RUCIO_CFG_ACCOUNT
      value: root
    - name: RUCIO_CFG_CLIENT_CERT
      value: /opt/rucio/etc/usercert.pem
    - name: RUCIO_CFG_CA_CERT
      value: /etc/grid-security/certificates/5fca1cb1.0
    - name: RUCIO_CFG_CLIENT_KEY
      value: /opt/rucio/etc/userkey.pem
    - name: RUCIO_CFG_CLIENT_X509_PROXY
      value: $X509_USER_PROXY
    - name: X509_USER_CERT
      value: /opt/rucio/etc/usercert.pem
    - name: X509_USER_KEY
      value: /opt/rucio/etc/userkey.pem
  volumes:
  - name: usercert
    secret:
      secretName: clients-user-cert
  - name: userkey
    secret:
      secretName: clients-user-key
  - name: ca
    secret:
      secretName: clients-rucio-ca-bundle
      defaultMode: 0644
     

