replicaCount: 1
## authReplicaCount gives the number of authentication server pods to run
authReplicaCount: 1
traceReplicaCount: 0

image:
  repository: rucio/rucio-server
  tag: release-1.29.10

config:
  api:
    endpoints: "accountlimits, accounts, archives, config, credentials, dids, export, heartbeats, identities, import, lifetime_exceptions, locks, meta, ping, redirect, replicas, requests, rses, rules, scopes, subscriptions"
  database:
    default: "postgresql://rucio:secret@postgres-postgresql/rucio"
    schema: "test"

ingress:
  enabled: true
  annotations:
          #nginx.ingress.kubernetes.io/rewrite-target: /$1
    # kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/frontend-entry-points: http
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
  path: /
  hosts: 
    - rucio-server.info

authIngress:
  enabled: true
  annotations:
          #nginx.ingress.kubernetes.io/rewrite-target: /$1
    # kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/frontend-entry-points: http
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
  path: /
  hosts: 
    - rucio-auth.info
