---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fts-mysql
  labels:
    app: fts
spec:
  selector:
    matchLabels:
      app: fts
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fts
        tier: mysql
    spec:
      containers:
      - name: fts-mysql
        image: mysql:5
        env:
        - name: MYSQL_USER
          value: fts
        - name: MYSQL_PASSWORD
          value: fts
        - name: MYSQL_ROOT_PASSWORD
          value: fts
        - name: MYSQL_DATABASE
          value: fts
        ports:
        - name: mysql
          containerPort: 3306
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: ftsdb
  labels:
    app: ftsdb
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    app: fts
    tier: mysql
