---
apiVersion: v1
kind: Pod
metadata:
  name: xrd1
  labels:
    app: xrd1
spec:
  containers:
    - name: xrd1
      image: rucio/test-xrootd
      env:
        - name: XRDPORT
          value: "1094"
      ports:
        - name: xrd1
          containerPort: 1094
          protocol: TCP
      volumeMounts:
        - name: hostcert
          mountPath: /tmp/xrdcert.pem
          subPath: tls.cert
        - name: hostcert
          mountPath: /tmp/xrdkey.pem
          subPath: tls.key
        - name: ca-cert
          mountPath: /etc/grid-security/certificates/5fca1cb1.0
          subPath: tls.cert
  volumes:
  - name: hostcert
    secret:
      secretName: hostcert-xrd1
  - name: ca-cert
    secret:
      secretName: ca-cert
---
apiVersion: v1
kind: Service
metadata:
  name: xrd1
  labels:
    app: xrd1
spec:
  ports:
    - port: 1094
      targetPort: 1094
      protocol: TCP
      name: xrd1

  selector:
    app: xrd1

---
apiVersion: v1
kind: Pod
metadata:
  name: xrd2
  labels:
    app: xrd2
spec:
  containers:
    - name: xrd2
      image: rucio/test-xrootd
      env:
        - name: XRDPORT
          value: "1094"
      ports:
        - name: xrd2
          containerPort: 1094
          protocol: TCP
      volumeMounts:
        - name: hostcert
          mountPath: /tmp/xrdcert.pem
          subPath: tls.cert
        - name: hostcert
          mountPath: /tmp/xrdkey.pem
          subPath: tls.key
        - name: ca-cert
          mountPath: /etc/grid-security/certificates/5fca1cb1.0
          subPath: tls.cert
  volumes:
  - name: hostcert
    secret:
      secretName: hostcert-xrd2
  - name: ca-cert
    secret:
      secretName: ca-cert
---
apiVersion: v1
kind: Service
metadata:
  name: xrd2
  labels:
    app: xrd2
spec:
  ports:
    - port: 1094
      targetPort: 1094
      protocol: TCP
      name: xrd2

  selector:
    app: xrd2

---
apiVersion: v1
kind: Pod
metadata:
  name: xrd3
  labels:
    app: xrd3
spec:
  containers:
    - name: xrd3
      image: rucio/test-xrootd
      env:
        - name: XRDPORT
          value: "1094"
      ports:
        - name: xrd3
          containerPort: 1094
          protocol: TCP
      volumeMounts:
        - name: hostcert
          mountPath: /tmp/xrdcert.pem
          subPath: tls.cert
        - name: hostcert
          mountPath: /tmp/xrdkey.pem
          subPath: tls.key
        - name: ca-cert
          mountPath: /etc/grid-security/certificates/5fca1cb1.0
          subPath: tls.cert
  volumes:
  - name: hostcert
    secret:
      secretName: hostcert-xrd3
  - name: ca-cert
    secret:
      secretName: ca-cert
---
apiVersion: v1
kind: Service
metadata:
  name: xrd3
  labels:
    app: xrd3
spec:
  ports:
    - port: 1094
      targetPort: 1094
      protocol: TCP
      name: xrd3

  selector:
    app: xrd3

---
